plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
keyed_groups:
  - key: tags.OS          # optional: group by OS tag
  - key: tags.Environment # optional: group by Environment tag
hostnames:
  - public_dns_name
filters:
  instance-state-name: running
compose:
  ansible_host: public_dns_name
  ansible_user: |
    'ec2-user' if tags.get('OS') == 'amazon-linux' else
    'ec2-user' if tags.get('OS') == 'rhel' else
    'ubuntu'
