plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
keyed_groups:
  - key: tags.Role    # Group by OS tag
    separator: ""
hostnames:
  - name: 'ip-address'
filters:
  instance-state-name: running
compose:
  ansible_host: 'ip-address'
  ansible_user: |
    (
      'ec2-user' if tags.get('OS') == 'amazon-linux' or tags.get('OS') == 'rhel' else 'ubuntu'
    )
  ansible_ssh_private_key_file: ~/ansible-rsa-keypair.pem
  ansible_python_interpreter: /usr/bin/python3
