plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
keyed_groups:
  - key: tags.OS    # Group by OS tag
hostnames:
  - name: private_ip_address
    separator: '_'
    prefix: 'tag:Name' 
filters:
  instance-state-name: running
compose:
  ansible_host: private_ip_address
  ansible_user: |
    (
      'ec2-user' if tags.get('OS') == 'amazon-linux' or 'rhel' else
      'ubuntu'
    )
  ansible_ssh_private_key_file: ~/ansible-rsa-keypair.pem
