- name: Install mariadb package (amazon linux)
  tags: db, mariadb
  ansible.builtin.yum:
        name: mariadb1011-server
        state: latest
  when: ansible_distribution == "Amazon"

- name: Start and enable MariaDB service
  ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
