- name: Install mariadb package (amazon linux)
  tags: db, mariadb
  ansible.builtin.yum:
        name: "{{ mariadb_package_version }}"
        state: latest
  when: ansible_distribution == "Amazon"

- name: Start and enable MariaDB service
  ansible.builtin.service:
        name: "{{ mariadb_service_name }}"
        state: started
        enabled: true
