- name: Install unzip
  ansible.builtin.package:
        name: unzip
        state: latest

- name: Install terraform
  ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '755'
        remote_src: true
