---

- hosts: all
  become: true
  pre_tasks:

    - name: Install updates Ubuntu
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install updates Redhat and amazon linux
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution in ["RedHat", "Amazon"]

- hosts: web
  become: true
  tasks:
    
    - name: Install apache and PHP in web server (RHEL)
      dnf:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

- hosts: db
  become: true
  tasks:

    - name: Install mariadb package (amazon linux)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Amazon"

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes
