---

- hosts: all
  become: true
  pre_tasks:

    - name: Install updates Ubuntu
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install updates Redhat and amazon linux
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution in ["RedHat", "Amazon"]

- hosts: web
  gather_facts: true
  become: true
  tasks:
    
    - name: Install apache and PHP in web server (RHEL)
      dnf:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy test HTML page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Apache is working on {{ inventory_hostname }}</h1>"
        owner: apache
        group: apache
        mode: '0644'
  
    - name: Deploy test PHP page
      copy:
        dest: /var/www/html/info.php
        content: "<?php phpinfo(); ?>"
        owner: apache
        group: apache
        mode: '0644'
  
    - name: Verify Apache is running via HTTP
      uri:
        url: "http://{{ ansible_host }}/"
        return_content: yes
      register: apache_check

    - name: Show verification output
      debug:
        msg: "{{ apache_check.content | truncate(100) }}"


- hosts: db
  become: true
  tasks:

    - name: Install mariadb package (amazon linux)
      yum:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Amazon"

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes
