---

- name: Install updates on ubuntu, Amazon linux and redhat
  hosts: all
  become: true
  pre_tasks:

    - name: Install updates Ubuntu
      tags: ubuntu, update
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install updates Redhat and amazon linux
      tags: update, redhat, amazonlinux
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution in ["RedHat", "Amazon"]

- name: Install apache on web server
  hosts: web
  gather_facts: true
  become: true
  roles:
    - web

- name: Install maria db on amazon linux
  hosts: db
  become: true
  roles:
    - db

- name: Install unzip and terraform on control node
  hosts: control
  become: true
  roles:
    - control

- name: Create a user, add ssh key and sudoer file
  hosts: all
  become: true
  roles:
    - base
